PREFIX se_sec_nvd_vocab: <https://ontology.siemens-energy.com/nvd/>
PREFIX schema: <http://schema.org/>
PREFIX software_vocab: <http://ontologies.siemens-energy.com/software/>
PREFIX software_package: <https://data.siemens-energy.com/cybersec/package/>

SELECT DISTINCT ?cve ?cve_description ?dependecy_name ?dependecy
WHERE {
    GRAPH <urn:python> {
    	?root software_vocab:hasDependency+ ?dependecy .
    	BIND(REPLACE(STR(?dependecy), "^.*/([^/]+)$", "$1") AS ?dependecy_name)
	}
	GRAPH <urn:nvd> {
    	?cve se_sec_nvd_vocab:description ?cve_description .
    } 
    FILTER (contains(?cve_description,?dependecy_name)) 
}