PREFIX software_vocab: <http://ontologies.siemens-energy.com/software/>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX se_sec_nvd_vocab: <https://ontology.siemens-energy.com/nvd/>
PREFIX cve: <https://data.siemens-energy.com/cybersec/cve/>

SELECT ?package ?downward_dependecy ?upward_dependency
WHERE {
    ?package rdf:type software_vocab:Software_package .
    ?package software_vocab:hasDependency ?downward_dependecy .
    FILTER NOT EXISTS {
    	?upward_dependency software_vocab:hasDependency ?package .
  }
}